<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace mass body_width body_height mesh_file *origin *inertia">
    
    <link name="base_link"></link>
    <joint name="base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="base_link" />
      <child link="base_link_inertia" />
    </joint>
    <link name="base_link_inertia">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="inertia" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/${mesh_file}"
            scale="1 1 1" />
          <!--box size="${body_width} ${body_width} ${body_height}"/--> <!-- [m] [m] [m] -->
        </geometry>
      </visual>

      <!--collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/${mesh_file}"
            scale="1 1 1" />
          <box size="${body_width} ${body_width} ${body_height}" />
        </geometry>
      </collision-->
    </link>

    <!-- IMU -->
    <link name="imu_link">
      <inertial>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0"
          izz="0.00001" />
        <mass value="0.01" />  <!-- [kg] -->
        <origin xyz="0 0 0" rpy="0 0 0" />
      </inertial>
    </link>
    <!-- IMU joint -->
    <joint name="imu_joint" type="revolute">
      <!--origin xyz="0 0 0" rpy="3.1416 0 0" / -->
      <parent link="base_link" />
      <child link="imu_link" />
      <limit upper="0" lower="0" effort="0" velocity="0" />
    </joint>
    
    <!-- attach multirotor_base_plugin to the base_link -->
    <gazebo>
      <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="rosbag">
        <robotNamespace>$(arg name)</robotNamespace>
        <linkName>base_link</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
  </xacro:macro>

  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color *origin *inertia">
    <joint name="rotor_${motor_number}_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- TODO(ff): not currently set because it's not yet supported -->
      <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
      <parent link="${parent}" />
      <child link="rotor_${motor_number}" />

    </joint>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz> 
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
    <link name="rotor_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!-- <cylinder length="0.005" radius="${radius_rotor}"/> --> <!-- [m] -->
          <mesh filename="package://mmuav_description/meshes/propeller_${direction}.dae"
            scale="0.001 0.001 0.001" />
          <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo>
      <plugin name="${suffix}_motor_model" filename="librotors_gazebo_motor_model.so">
        <jointName>rotor_${motor_number}_joint</jointName>
        <linkName>rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandTopic>${robot_namespace}/command/motors</commandTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorVelocityTopic>${robot_namespace}/motor_vel/${motor_number}</motorVelocityTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
    <gazebo reference="rotor_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>

  <!-- We add a <transmission> block for every joint that we wish to actuate. -->
  <xacro:macro name="transmisija" params="trans_number joint_name">
    <transmission name="transmission_${trans_number}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
         <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_${trans_number}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <xacro:macro name="landing_gear" params="gear_num parent mass dim_x dim_y dim_z *origin *inertia">
    <joint name="land_gear_${gear_num}" type="fixed">
      <xacro:insert_block name="origin"/>
      <axis xyz="0 0 1"/>
      <parent link="${parent}"/>
      <child link="land_gear_${gear_num}"/>
    </joint>
    <link name="land_gear_${gear_num}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.01 0.01 0.0001"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${dim_x} ${dim_y} ${dim_z}"/>
        </geometry>
      </collision>
      <inertial>
         <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${mass}"/>
        <xacro:insert_block name="inertia"/>
      </inertial>
    </link>

  </xacro:macro>

  <!-- Camera macro. Adds a box representing a camera below the UAV
  
  @param camera_link Length of the camera box
  @param camera_mass Mass of the camera 
  @param parent Parent link on which the camera will be fixed
  @param *origin Block argument defining the origin of the camera with 
  reference to the parent link.
  @param *inertia Block argument defining camera inertia.
  -->
  <xacro:macro name="cam" params="camera_link camera_mass parent *origin *inertia">

    <!-- Camera link -->
    <link name="camera_box">

      <!--collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
      </collision-->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="${camera_mass}" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:insert_block name="inertia"/>
      </inertial>

    </link>

    <!-- Camera joint with reference to the parent link -->
    <joint name="camera_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="camera_box"/>
    </joint>

    <!-- camera -->
    <gazebo reference="camera_box">
      <sensor type="camera" name="camera1">
        <update_rate>30.0</update_rate>
        
        <camera name="head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>800</width>
            <height>800</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>

        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>morus/camera1</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>camera_box</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>

      </sensor>
    </gazebo>

  </xacro:macro>

  <xacro:macro name="manipulator"
  params="parent suffix *axis *origin">
    <!--_____________________________________________________________-->
    <!--LINK1 manipulator2uav-->
    <!--_____________________________________________________________-->
    <link name='link_manipulator2uav_${suffix}'>
      
      <inertial>
        <mass value="0.022" />
        <origin rpy="0 0 0" xyz="0 -0.03190 0.00346"/>
        <inertia
          ixx="0.00001" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00001" iyz="0"
          izx="0.0" izy="0" izz="0.00001"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/manipulator2uav.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK1.2 dynamixel1-->
    <!--_____________________________________________________________-->
    <link name='link_dynamixel1_${suffix}'>
      <inertial>
        <mass value="0.055" />
        <origin rpy="0 0 0" xyz="0.01261097 0 0.00120978"/>
        <inertia
          ixx="0.00000885" ixy="0" ixz="0.00000024"
          iyx="0" iyy="0.00001597" iyz="0"
          izx="-0.00000024" izy="0" izz="0.00001335"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/AX12.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 F3-->
    <!--_____________________________________________________________-->
    <link name='link_F3_${suffix}'>
      <inertial>
        <mass value="0.003" />
        <origin rpy="0 0 0" xyz="0.00000191 0.00240389 0"/>
        <inertia
          ixx="0.00000044" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00000061" iyz="0"
          izx="0.0" izy="0" izz="0.00000019"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/F3.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 F4-->
    <!--_____________________________________________________________-->
    <link name='link_F4_${suffix}'>
      <inertial>
        <mass value="0.014" />
        <origin rpy="0 0 0" xyz="0 -0.0304 -0.0086"/>
        <inertia
          ixx="0.00001183" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00000252" iyz="-0.00000390"
          izx="0.0" izy="-0.00000390" izz="0.00001050"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/F4.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 dynamixel2-->
    <!--_____________________________________________________________-->
    <link name='link_dynamixel2_${suffix}'>
      <inertial>
        <mass value="0.055" />
        <origin rpy="0 0 0" xyz="0.01261097 0 0.00120978"/>
        <inertia
          ixx="0.00000885" ixy="0" ixz="0.00000024"
          iyx="0" iyy="0.00001597" iyz="0"
          izx="-0.00000024" izy="0" izz="0.00001335"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/AX12.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 gripper 1-->
    <!--_____________________________________________________________-->
    <link name='link_gripper1_${suffix}'>
      <inertial>
        <mass value="0.010" />
        <origin rpy="0 0 0" xyz="0.00028510 0.00103830 0.00134070"/>
        <inertia
          ixx="0.00000114" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00000156" iyz="0"
          izx="0.0" izy="0" izz="0.00000125"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/gripper_part1.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK3 gripper 2-->
    <!--_____________________________________________________________-->
    <link name='link_gripper2_${suffix}'>
      <inertial>
        <mass value="0.015" />
        <origin rpy="0 0 0" xyz="0.005537 0.00103806 0.00134058"/>
        <inertia
          ixx="0.00000281" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00000248" iyz="0"
          izx="0.0" izy="0" izz="0.00000391"/>
      </inertial>
            
      <visual>
        <origin xyz="0.02047 -0.00104 0.00135" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/gripper_part2.dae"
            scale="1 1 1" />
        </geometry>
      </visual>
    </link>

    <!--_____________________________________________________________-->
    <!--JOINT1 FIXED manipulator2uav-->
    <!--_____________________________________________________________-->
    <joint name="joint_manipulator2uav_${suffix}" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="link_manipulator2uav_${suffix}"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT1 CONTINOUS dynamixel1-->
    <!--_____________________________________________________________-->
    <joint name="joint_dynamixel1_${suffix}" type="revolute">
      <parent link="link_manipulator2uav_${suffix}"/>
      <child link="link_dynamixel1_${suffix}"/>
      <origin xyz="0 0 0" rpy="${PI} 0 ${-PI/2}" />
      <limit upper="6" lower="-6" effort="1.5" velocity="1"/>
      <axis xyz="0 0 1" />
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 FIXED F3-->
    <!--_____________________________________________________________-->
    <joint name="joint_F3_${suffix}" type="fixed">
        <origin xyz="0.04150716806 0 0" rpy="0 0 ${PI/2}" />
        <parent link="link_dynamixel1_${suffix}"/>
        <child link="link_F3_${suffix}"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 FIXED F4-->
    <!--_____________________________________________________________-->
    <joint name="joint_F4_${suffix}" type="fixed">
        <origin xyz="0 -0.05249560744 0" rpy="0 0 ${PI}" />
        <parent link="link_F3_${suffix}"/>
        <child link="link_F4_${suffix}"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 CONTINOUS dynamixel2-->
    <!--_____________________________________________________________-->
    <joint name="joint_dynamixel2_${suffix}" type="revolute">
      <parent link="link_F4_${suffix}"/>
      <child link="link_dynamixel2_${suffix}"/>
      <origin xyz="0 0 0" rpy="0 0 ${-PI/2}" />
      <limit upper="6" lower="-6" effort="0.3" velocity="0.1"/>
      <axis xyz="0 0 1" />
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 FIXED gripper part1-->
    <!--_____________________________________________________________-->
    <joint name="joint_gripper1_${suffix}" type="fixed">
        <origin xyz="0.04842 -0.00104 -0.00134" rpy="0 0 0" />
        <parent link="link_dynamixel2_${suffix}"/>
        <child link="link_gripper1_${suffix}"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT3 CONTINOUS gripper-->
    <!--_____________________________________________________________-->
    <joint name="joint_gripper2_${suffix}" type="revolute">
      <parent link="link_gripper1_${suffix}"/>
      <child link="link_gripper2_${suffix}"/>
      <origin xyz="0.01265 0.00104 -0.00134" rpy="0 0 ${PI}" />
      <limit upper="6" lower="-6" effort="0.05" velocity="0.01"/>
      <axis xyz="0 0 1" />
    </joint>

  </xacro:macro>

  <xacro:macro name="force_sensor" 
    params="*origin">

    <link name="world"></link>

    <!--_____________________________________________________________-->
    <!--LINK1 force sensor stand-->
    <!--_____________________________________________________________-->
    <link name='link_force_sensor_stand'>
      
      <inertial>
        <mass value="2.0" />
        <origin rpy="0 0 0" xyz="0.38508257 0.46818651 1.04028639"/>
        <inertia
          ixx="0.23434322" ixy="0" ixz="0.0"
          iyx="0" iyy="0.01547123" iyz="0"
          izx="0.0" izy="0" izz="0.23434322"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_stand.dae"
            scale="1 1 1" />
        </geometry>
      </visual>

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_stand.dae"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 force sensor mount bottom-->
    <!--_____________________________________________________________-->
    <link name='link_force_sensor_bottom_mount'>
      
      <inertial>
        <mass value="0.05" />
        <origin rpy="0 0 0" xyz="0.0 0.00206111 0.0"/>
        <inertia
          ixx="0.00002139" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00004241" iyz="0"
          izx="0.0" izy="0" izz="0.00002139"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_mount_bottom.dae"
            scale="1 1 1" />
        </geometry>
      </visual>

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_mount_bottom.dae"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>
    <!--_____________________________________________________________-->
    <!--LINK2 force sensor mount top-->
    <!--_____________________________________________________________-->
    <link name='link_force_sensor_top_mount'>
      
      <inertial>
        <mass value="0.080" />
        <origin rpy="0 0 0" xyz="0.01903151 0.01661061 0.02154592"/>
        <inertia
          ixx="0.00059994" ixy="0" ixz="0.0"
          iyx="0" iyy="0.00059994" iyz="0"
          izx="0.0" izy="0" izz="0.00119615"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_mount_top.dae"
            scale="1 1 1" />
        </geometry>
      </visual>

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mmuav_description/meshes/forcesensor_mount_top.dae"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>
    <!--_____________________________________________________________-->
    <!--JOINT1 FIXED force_sensor_stand-->
    <!--_____________________________________________________________-->
    <joint name="joint_force_sensor_stand" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="world"/>
        <child link="link_force_sensor_stand"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 FIXED joint_force_sensor_mount_bottom-->
    <!--_____________________________________________________________-->
    <joint name="joint_force_sensor_mount_bottom" type="fixed">
        <origin xyz="0 1.003 0" rpy="${PI} 0 0" />
        <parent link="link_force_sensor_stand"/>
        <child link="link_force_sensor_bottom_mount"/>
    </joint>
    <!--_____________________________________________________________-->
    <!--JOINT2 FIXED force_sensor_mount_top-->
    <!--_____________________________________________________________-->
    <joint name="joint_force_sensor_mount_top" type="revolute">
        <origin xyz="-0.01903 -0.05153 0.01661" rpy="${-PI/2} 0 0" />
        <parent link="link_force_sensor_bottom_mount"/>
        <child link="link_force_sensor_top_mount"/>
        <axis xyz="0 0 1" />
        <limit effort="0" velocity="0" lower="0" upper="0" />
    </joint>
  </xacro:macro>

<xacro:macro name="screw" 
    params="*origin">

    <link name="base_link"></link>

    <!--_____________________________________________________________-->
    <!--LINK1 force sensor stand-->
    <!--_____________________________________________________________-->
    <link name='link_screw'>
      
      <inertial>
        <mass value="0.5" />
        <origin rpy="0 0 0" xyz="0.02100388 0.01819119 0.05027511"/>
        <inertia
          ixx="0.00020051" ixy="0" ixz="-0.00000019"
          iyx="0" iyy="0.00020054" iyz="0.00000001"
          izx="-0.00000019" izy="0.00000001" izz="0.00006377"/>
      </inertial>
            
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mmuav_description/meshes/screw.dae"
            scale="1 1 1" />
        </geometry>
      </visual>

      <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mmuav_description/meshes/screw.dae"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>
    
    <!--_____________________________________________________________-->
    <!--JOINT1 FIXED force_sensor_stand-->
    <!--_____________________________________________________________-->
    <joint name="joint_screw" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="base_link"/>
        <child link="link_screw"/>
    </joint>
   
  </xacro:macro>

  <!-- Definition of movable mass macro -->
  <xacro:macro name="movable_mass" params="mass_number parent mass dimension path_len color x_axis y_axis z_axis orientation *origin *inertia">
    <joint name="stick_to_movable_mass_${mass_number}" type="prismatic">
      <xacro:insert_block name="origin"/>
      <axis xyz="${x_axis} ${y_axis} ${z_axis}"/>
      <parent link="${parent}"/>
      <child link="movable_mass_${mass_number}"/>
      <limit lower="${-path_len/2}" upper="${path_len/2}" effort="10000" velocity="20"/>
      <dynamics damping="10" />
    </joint>
    <link name="movable_mass_${mass_number}">
      <visual>
        <origin rpy="0 0 ${orientation}" xyz="0 0 ${0*dimension/2}"/>
        <geometry>
          <box size="${1*dimension} ${1*dimension} ${1*dimension}"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${0*dimension/2}"/>
        <geometry>
          <box size="${1*dimension} ${1*dimension} ${1*dimension}"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${0*dimension/2}"/>
        <mass value="${mass}"/>
        <xacro:insert_block name="inertia"/>
      </inertial>
    </link>

    <gazebo reference="movable_mass_${mass_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>


</robot>