<?xml version="1.0"?>

<robot name="uav" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="15" />
  <xacro:property name="mesh_file" value="3DR_Arducopter.dae" />
  <xacro:property name="mass" value="2.083" />  <!-- [kg] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.20842" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.314" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.04579" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1524" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1475" /> <!-- [rad/s] -->
  <xacro:property name="sin45" value="0.7071068" />
  <xacro:property name="cos45" value="0.7071068" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- aditional arm properties -->
  <xacro:property name="arm_offset" value="0.1" /> <!-- [m] 0.0457-->

  <!-- Moving masses properties -->

  <xacro:property name="mm_mass" value="0.208" />
  <xacro:property name="mm_dimension" value="0.035" />
  <xacro:property name="mm_ver_offset" value="0.0" />
  <xacro:property name="mm_path_len" value="0.17" />

  <xacro:property name="imu_mass" value="0.02"/>
  <xacro:property name="imu_size" value="0.01"/>

  <xacro:property name="sin45" value="0.7071" />
  <xacro:property name="cos45" value="0.7071" />
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="tilt_angle" value="0.0"/>


  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
  <!--<inertia ixx="0.00528525" ixy="0.0" ixz="0.0" iyy="0.00528250" iyz="0.0" izz="0.0104" />  [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
    <inertia ixx="0.0826944" ixy="0.0" ixz="0.0" iyy="0.0826944" iyz="0.0" izz="0.0104" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] identificirani Ixx Iyy-->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=5mm, width=31mm -->
  <xacro:property name="rotor_inertia">
    <inertia
    ixx="${1/12 * mass_rotor * (0.031 * 0.031 + 0.005 * 0.005) * rotor_velocity_slowdown_sim}"
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.005 * 0.005) * rotor_velocity_slowdown_sim}"
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.031 * 0.031) * rotor_velocity_slowdown_sim}"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find mmuav_description)/urdf/multirotor_base.urdf.xacro" />

  <!-- IMU inertia (Pixhawk) -->
  <xacro:property name="imu_inertia">
    <inertia
    ixx="${(imu_mass * imu_size * imu_size)/6}"
    iyy="${(imu_mass * imu_size * imu_size)/6}"
    izz="${(imu_mass * imu_size * imu_size)/6}"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg name)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${mesh_file}">
    <origin xyz="0 0 0" rpy="0 0 ${-PI/4}"/>
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <!--<origin xyz="${cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 ${-tilt_angle} 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <!--<origin xyz="${cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${0*arm_length} ${-1*arm_length} ${rotor_offset_top}" rpy="${-tilt_angle} 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <!--<origin xyz="${-cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${0*arm_length} ${1*arm_length} ${rotor_offset_top}" rpy="${tilt_angle} 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <!--<origin xyz="${-cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${-1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 ${tilt_angle} 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <link name='link01'>
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 -0.03" rpy="0 0 0"/>
      <inertia
        ixx="0.05" ixy="0" ixz="0"
        iyx="0" iyy="0.05" iyz="0"
        izx="0" izy="0" izz="0.05"/>
    </inertial>

    <visual>
      <origin xyz="0 0 -0.03" rpy="0 0 0" />
      <geometry>
        <cylinder length="0.08" radius="0.015"/>
      </geometry>
    </visual>
  </link>


  <link name='con1'>
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 -0.07" rpy="0 0 0"/>
      <inertia
        ixx="0.05" ixy="0" ixz="0"
        iyx="0" iyy="0.05" iyz="0"
        izx="0" izy="0" izz="0.05"/>
    </inertial>

    <visual>
      <origin xyz="0 0 -0.07" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </visual>
  </link>

  <link name='link12'>
    <inertial>
      <mass value="0.001" />
      <origin xyz="-0.113137 0.113137 -0.07" rpy="0 0 0"/>
      <inertia
        ixx="0.05" ixy="0" ixz="0"
        iyx="0" iyy="0.05" iyz="0"
        izx="0" izy="0" izz="0.05"/>
    </inertial>

    <visual>
      <origin xyz="-0.113137 0.113137 -0.07" rpy="0.758398 1.5708 0" />
      <geometry>
        <cylinder length="0.32" radius="0.015"/>
      </geometry>
    </visual>
  </link>

  <link name='con2'>
    <inertial>
      <mass value="0.001" />
      <origin xyz="-0.226274 0.226274 -0.07" rpy="0 0 0"/>
      <inertia
        ixx="0.5" ixy="0" ixz="0"
        iyx="0" iyy="0.5" iyz="0"
        izx="0" izy="0" izz="0.5"/>
    </inertial>

    <visual>
      <origin xyz="-0.226274 0.226274 -0.07" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </visual>
  </link>

  <link name='link23'>
    <inertial>
      <mass value="0.001" />
      <origin xyz="-0.282843 0.282843 -0.07" rpy="0 0 0"/>
      <inertia
        ixx="0.5" ixy="0" ixz="0"
        iyx="0" iyy="0.5" iyz="0"
        izx="0" izy="0" izz="0.5"/>
    </inertial>

    <visual>
      <origin xyz="-0.282843 0.282843 -0.07" rpy="0.758398 1.5708 0" />
      <geometry>
        <cylinder length="0.16" radius="0.015"/>
      </geometry>
    </visual>
  </link>


  <joint name="base_to_link01" type="fixed">
    <parent link="base_link"/>
    <child link="link01"/>
  </joint>

  <joint name="link01_to_con1" type="fixed">
    <parent link="link01"/>
    <child link="con1"/>
  </joint>

  <joint name="con1_to_link12" type="continuous">
    <parent link="con1"/>
    <child link="link12"/>
    <limit upper="3.14" lower="-3.14" effort="10000000" velocity="20"/>
    <axis xyz="0 0 1" />
    <dynamics damping="0.07" friction="0.0"/>
  </joint>

  <joint name="link12_to_con2" type="fixed">
    <parent link="link12"/>
    <child link="con2"/>
  </joint>

  <joint name="con2_to_link23" type="continuous">
    <parent link="con2"/>
    <child link="link23"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <limit upper="3.14" lower="-3.14" effort="10000000" velocity="20"/>
    <axis xyz="0 0 1" />
    <dynamics damping="0.07" friction="0.0"/>
  </joint>

  <!--
  <origin xyz="0 0 -0.3" rpy="0 0 0"/>
  <origin xyz="0 0 -0.07" rpy="0 0 0"/>
  <origin xyz="0 0 -0.07" rpy="0 0 0"/>
  <origin xyz="-0.226274 0.226274 -0.07" rpy="0 0 -0.07"/>
  <origin xyz="-0.226274 0.226274 -0.07" rpy="0 0 0"/>
  -->

  <xacro:transmisija
    trans_number="0"
    joint_name="con1_to_link12">
  </xacro:transmisija>

  <xacro:transmisija
    trans_number="1"
    joint_name="con2_to_link23">
  </xacro:transmisija>

</robot>
