<?xml version="1.0"?>

<robot name="uav" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="rotor_velocity_slowdown_sim" value="15" />
  <xacro:property name="mesh_file" value="3DR_Arducopter.dae" />
  <xacro:property name="mass" value="2.083" />  <!-- [kg] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.20842" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.314" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.04579" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1524" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="8.54858e-06" /> <!-- [kg*m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1475" /> <!-- [rad/s] -->
  <xacro:property name="sin45" value="0.7071068" />
  <xacro:property name="cos45" value="0.7071068" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- aditional arm properties -->
  <xacro:property name="arm_offset" value="0.1" /> <!-- [m] 0.0457-->

  <!-- Moving masses properties -->

  <xacro:property name="mm_mass" value="0.208" />
  <xacro:property name="mm_dimension" value="0.035" />
  <xacro:property name="mm_ver_offset" value="0.0" />
  <xacro:property name="mm_path_len" value="0.17" />

  <xacro:property name="imu_mass" value="0.02"/>
  <xacro:property name="imu_size" value="0.01"/>

  <xacro:property name="sin45" value="0.7071" />
  <xacro:property name="cos45" value="0.7071" />
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="tilt_angle" value="0.0"/>


  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
  <!--<inertia ixx="0.00528525" ixy="0.0" ixz="0.0" iyy="0.00528250" iyz="0.0" izz="0.0104" />  [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
    <inertia ixx="0.0826944" ixy="0.0" ixz="0.0" iyy="0.0826944" iyz="0.0" izz="0.0104" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] identificirani Ixx Iyy-->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=5mm, width=31mm -->
  <xacro:property name="rotor_inertia">
    <inertia
    ixx="${1/12 * mass_rotor * (0.031 * 0.031 + 0.005 * 0.005) * rotor_velocity_slowdown_sim}"
    iyy="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.005 * 0.005) * rotor_velocity_slowdown_sim}"
    izz="${1/12 * mass_rotor * (4 * radius_rotor * radius_rotor + 0.031 * 0.031) * rotor_velocity_slowdown_sim}"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find mmuav_description)/urdf/multirotor_base.urdf.xacro" />

  <!-- IMU inertia (Pixhawk) -->
  <xacro:property name="imu_inertia">
    <inertia
    ixx="${(imu_mass * imu_size * imu_size)/6}"
    iyy="${(imu_mass * imu_size * imu_size)/6}"
    izz="${(imu_mass * imu_size * imu_size)/6}"
    ixy="0.0" ixz="0.0"  iyz="0.0" /> <!-- [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] [kg*m^2] -->
  </xacro:property>

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="$(arg name)"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    mesh_file="${mesh_file}">
    <origin xyz="0 0 0" rpy="0 0 ${-PI/4}"/>
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <!--<origin xyz="${cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 ${-tilt_angle} 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <!--<origin xyz="${cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${0*arm_length} ${-1*arm_length} ${rotor_offset_top}" rpy="${-tilt_angle} 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue">
    <!--<origin xyz="${-cos45*arm_length} ${sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${0*arm_length} ${1*arm_length} ${rotor_offset_top}" rpy="${tilt_angle} 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="$(arg name)"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red">
    <!--<origin xyz="${-cos45*arm_length} ${-sin45*arm_length} ${rotor_offset_top}" rpy="0 0 0" />-->
    <origin xyz="${-1*arm_length} ${0*arm_length} ${rotor_offset_top}" rpy="0 ${tilt_angle} 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

<!--
  <xacro:camera_manipulator
    parent="base_link"
    link_mass="0.25"
    link_ixx="0.00004167"
    link_iyy="0.00854167"
    link_izz="0.00856667" >
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:camera_manipulator>
-->
<!--
  <xacro:camera_manipulator
    parent="base_link"
    link_mass="0.05"
    link_ixx="0.00000833"
    link_iyy="0.00170833"
    link_izz="0.00171333" >
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:camera_manipulator>
-->


  <xacro:camera_manipulator
    parent="base_link"
    link_mass="0.005"
    link_ixx="0.00000083"
    link_iyy="0.00017083"
    link_izz="0.00017133" >
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:camera_manipulator>

  <xacro:transmisija
    trans_number="0"
    joint_name="connector1_to_link1">
  </xacro:transmisija>

  <xacro:transmisija
    trans_number="1"
    joint_name="connector2_to_link2">
  </xacro:transmisija>

  <xacro:property name="camera_link" value="0.05" />
  <xacro:property name="camera_inertia">
    <inertia
    ixx="1e-8"
    iyy="1e-8"
    izz="1e-8"
    ixy="0.0" ixz="0.0" iyz="0.0" />
  </xacro:property>
  <xacro:property name="camera_mass" value="1e-5"/>

  <xacro:cam
    camera_link="${camera_link}"
    camera_mass="${camera_mass}"
    parent="link2">
    <origin xyz="-0.2121320344 0.2121320344 0.02" rpy="0 0 0"/>
    <xacro:insert_block name="camera_inertia"/>
  </xacro:cam>
  
</robot>
