uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: connector1_to_link1
    pid: {p: 1.2, i: 0.5, d: 0.0, i_clamp_max: 100, i_clamp_min: -100}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: connector2_to_link2
    pid: {p: 0.5, i: 0.5, d: 0.0, i_clamp_max: 100, i_clamp_min: -100}
