uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------

  joint1_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: connector1_to_link1
    pid: {p: 0.5, i: 0.0, d: 0.0}
  joint2_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: connector2_to_link2
    pid: {p: 0.25, i: 0.0, d: 0.0}
