uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_controller:
    type: effort_controllers/JointPositionController
    joint: con1_to_link12
    pid: {p: 1.8, i: 0.35, d: 0.0, i_clamp_max: 100, i_clamp_min: -100}
  joint2_controller:
    type: effort_controllers/JointPositionController
    joint: con2_to_link23
    pid: {p: 1.2, i: 0.0, d: 0.0, i_clamp_max: 100, i_clamp_min: -100}
