
# Position Controllers ---------------------------------------
joint1_left_position_controller:
  joint: joint_dynamixel1_left
  pid: {p: 0.3, i: 0, d: 0.0}
joint2_left_position_controller:
  joint: joint_dynamixel2_left
  pid: {p: 0.06, i: 0.0, d: 0.0}
joint3_left_position_controller:
  joint: joint_gripper2_left
  pid: {p: 0.004, i: 0.0, d: 0.0}
joint1_right_position_controller:
  joint: joint_dynamixel1_right
  pid: {p: 0.3, i: 0, d: 0.0}
joint2_right_position_controller:
  joint: joint_dynamixel2_right
  pid: {p: 0.06, i: 0.0, d: 0.0}
joint3_right_position_controller:
  joint: joint_gripper2_right
  pid: {p: 0.004, i: 0.0, d: 0.0}