
# Position Controllers ---------------------------------------
joint1_left_position_controller:
  command_topic: joint1_left_velocity_controller/command
  joint: joint_dynamixel1_left
  pid: {p: 8.0, i: 0.6, d: 0.0, high_limit: 6, low_limit: -6}
joint2_left_position_controller:
  command_topic: joint2_left_velocity_controller/command
  joint: joint_dynamixel2_left
  pid: {p: 8.0, i: 0.6, d: 0.0, high_limit: 6, low_limit: -6}
joint3_left_position_controller:
  command_topic: joint3_left_velocity_controller/command
  joint: joint_gripper2_left
  pid: {p: 6.0, i: 0.4, d: 0.0, high_limit: 6, low_limit: -6}
joint1_right_position_controller:
  command_topic: joint1_right_velocity_controller/command
  joint: joint_dynamixel1_right
  pid: {p: 8.0, i: 0.6, d: 0.0, high_limit: 6, low_limit: -6}
joint2_right_position_controller:
  command_topic: joint2_right_velocity_controller/command
  joint: joint_dynamixel2_right
  pid: {p: 8.0, i: 0.6, d: 0.0, high_limit: 6, low_limit: -6}
joint3_right_position_controller:
  command_topic: joint3_right_velocity_controller/command
  joint: joint_gripper2_right
  pid: {p: 6.0, i: 0.4, d: 0.0, high_limit: 6, low_limit: -6}