mmuav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_dynamixel1_left
    pid: {p: 500, i: 0, d: 0.0}
  joint2_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_dynamixel2_left
    pid: {p: 100, i: 0.0, d: 0.0}
  joint3_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper2_left
    pid: {p: 50, i: 0.0, d: 0.0}
  joint1_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_dynamixel1_right
    pid: {p: 500, i: 0, d: 0.0}
  joint2_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_dynamixel2_right
    pid: {p: 100, i: 0.0, d: 0.0}
  joint3_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_gripper2_right
    pid: {p: 1, i: 0.0, d: 0.0}