mmuav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers ---------------------------------------
  joint1_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q1_left
    pid: {p: 0.25, i: 0, d: 0.0}
  joint2_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q2_left
    pid: {p: 0.05, i: 0.0, d: 0.0}
  joint3_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q3_passive_left
    pid: {p: 0.008, i: 0.0, d: 0.0}
  joint1_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q1_right
    pid: {p: 0.25, i: 0, d: 0.0}
  joint2_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q2_right
    pid: {p: 0.05, i: 0.0, d: 0.0}
  joint3_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_q3_passive_right
    pid: {p: 0.008, i: 0.0, d: 0.0}