ruka:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers ---------------------------------------
  joint_1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 1, i: 0, d: 0}
  joint_2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 1, i: 0, d: 0}
  joint_3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 1, i: 0, d: 0}
  joint_4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 1, i: 0, d: 0}
